"""Paleta Auto-Hub - Light glass + Bento."""

# Fondo claro (gradiente base)
BG_DARK = "#F5F7FB"
BG_DEEP = "#EAF0F8"
BG_SIDEBAR = "#FFFFFF"

# Paneles glass sobre fondo claro
GLASS_BG = "#FFFFFF"
GLASS_BG_HOVER = "#F1F5F9"
GLASS_BG_ACTIVE = "#E7EEF8"
GLASS_BORDER = "#D8E1EE"
GLASS_BORDER_LIGHT = "#B9C8DC"
GLASS_BORDER_GLOW = "#4F7DF3"
GLASS_INPUT = "#F8FAFC"

# Alias legacy
BG_CARD = GLASS_BG
BG_CARD_HOVER = GLASS_BG_HOVER
BG_INPUT = GLASS_INPUT

# Texto
TEXT_PRIMARY = "#172033"
TEXT_SECONDARY = "#475569"
TEXT_MUTED = "#7C8A9F"

# Acentos (azul + teal)
ACCENT = "#2563EB"
ACCENT_HOVER = "#1D4ED8"
ACCENT_SOFT = "#5B8DEF"
CYAN = "#0891B2"
CYAN_HOVER = "#0E7490"
SUCCESS = "#059669"
WARNING = "#D97706"
DANGER = "#DC2626"

# Botones
BTN_PRIMARY = ACCENT
BTN_PRIMARY_HOVER = ACCENT_HOVER
BTN_PRIMARY_TEXT = "#FFFFFF"
BTN_SECONDARY = GLASS_BG
BTN_SECONDARY_HOVER = GLASS_BG_HOVER
BTN_SECONDARY_BORDER = GLASS_BORDER
BTN_SECONDARY_TEXT = TEXT_PRIMARY
BTN_GHOST_HOVER = GLASS_BG_HOVER
BTN_DANGER_BG = "#FFF1F2"
BTN_DANGER_HOVER = "#FFE4E6"
BTN_DANGER_BORDER = "#FDA4AF"
BTN_DANGER_TEXT = "#BE123C"
BTN_HEIGHT = 28
BTN_HEIGHT_SM = 26
BTN_HEIGHT_LG = 32
BTN_RADIUS = 8
BTN_FONT = ("Segoe UI", 11)
BTN_FONT_SM = ("Segoe UI", 10)

# Bento / glass geometry
BENTO_RADIUS = 10
BENTO_RADIUS_SM = 8
BENTO_GAP = 6
BENTO_PAD = 8

FONT_TITLE = ("Segoe UI", 15, "bold")
FONT_HEADING = ("Segoe UI", 13, "bold")
FONT_SUBTITLE = ("Segoe UI", 11)
FONT_BODY = ("Segoe UI", 11)
FONT_SMALL = ("Segoe UI", 10)
FONT_MONO = ("Cascadia Mono", 10)
FONT_LOGO = ("Segoe UI", 14, "bold")

TABLE_HEADER = ("#E7EEF8", "#E7EEF8")
TABLE_ROW_EVEN = ("#FFFFFF", "#FFFFFF")
TABLE_ROW_ODD = ("#F8FAFC", "#F8FAFC")
TABLE_HOVER = ("#EEF4FF", "#EEF4FF")
TABLE_SELECTED_ROW = ("#DBEAFE", "#DBEAFE")
TABLE_SELECTED_CELL = ("#2563EB", "#2563EB")
TABLE_SELECTED = TABLE_HOVER
