"""Paleta Auto-Hub."""

BG_DARK = "#F5F7FB"
BG_SIDEBAR = "#FFFFFF"

GLASS_BG = "#FFFFFF"
GLASS_BG_HOVER = "#F1F5F9"
GLASS_BORDER = "#D8E1EE"
GLASS_BORDER_GLOW = "#4F7DF3"
GLASS_INPUT = "#F8FAFC"

TEXT_PRIMARY = "#172033"
TEXT_SECONDARY = "#475569"
TEXT_MUTED = "#7C8A9F"

ACCENT = "#2563EB"
ACCENT_HOVER = "#1D4ED8"
ACCENT_SOFT = "#5B8DEF"
SUCCESS = "#059669"
WARNING = "#D97706"
DANGER = "#DC2626"
CARD_OK_BG = "#ECFDF5"
CARD_OK_BORDER = "#A7F3D0"
CARD_OK_SOFT = "#059669"
CARD_ERR_BG = "#FEF2F2"
CARD_ERR_BORDER = "#FECACA"
CARD_ERR_SOFT = "#DC2626"

BTN_PRIMARY = ACCENT
BTN_PRIMARY_HOVER = ACCENT_HOVER
BTN_PRIMARY_TEXT = "#FFFFFF"
BTN_SECONDARY = GLASS_BG
BTN_SECONDARY_HOVER = GLASS_BG_HOVER
BTN_SECONDARY_BORDER = GLASS_BORDER
BTN_SECONDARY_TEXT = TEXT_PRIMARY
BTN_GHOST_HOVER = GLASS_BG_HOVER
BTN_DANGER_BG = "#FFF1F2"
BTN_DANGER_HOVER = "#FFE4E6"
BTN_DANGER_BORDER = "#FDA4AF"
BTN_DANGER_TEXT = "#BE123C"
BTN_HEIGHT = 28
BTN_RADIUS = 8
BTN_FONT = ("Segoe UI", 11)

BENTO_RADIUS = 10

FONT_HEADING = ("Segoe UI", 13, "bold")
FONT_BODY = ("Segoe UI", 11)
FONT_SMALL = ("Segoe UI", 10)
FONT_LOGO = ("Segoe UI", 14, "bold")
